# Generated by Django 6.0.7 on 2026-08-01 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('medication', 'medication'), ('bed', 'bed'), ('general', 'general')], max_length=50)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('patientName', models.CharField(blank=True, max_length=255, null=True)),
                ('nextDose', models.TimeField(blank=True, null=True)),
                ('minutesLeft', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bedNumber', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], default='Available', max_length=50)),
                ('patientName', models.CharField(blank=True, max_length=255, null=True)),
                ('patientId', models.CharField(blank=True, max_length=255, null=True)),
                ('timeOccupied', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField(blank=True, null=True)),
                ('complaint', models.TextField()),
                ('categories', models.JSONField(default=list)),
                ('doctorConsulted', models.BooleanField(default=False)),
                ('doctorName', models.CharField(blank=True, max_length=255, null=True)),
                ('whoConsulted', models.CharField(blank=True, max_length=255, null=True)),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('earlyDismissal', models.BooleanField(default=False)),
                ('earlyDismissalReason', models.TextField(blank=True, null=True)),
                ('fetcherName', models.CharField(blank=True, max_length=255, null=True)),
                ('nurseNotes', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('followUp', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Consultation', 'Consultation'), ('Non-Consultation', 'Non-Consultation')], default='Consultation', max_length=50)),
                ('prescriptionImage', models.URLField(blank=True, null=True)),
                ('transferred', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Low Stock', 'Low Stock')], default='Normal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Outsider', 'Outsider')], max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergencyContact', models.CharField(blank=True, max_length=255, null=True)),
                ('emergencyPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('yearLevel', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine', models.CharField(max_length=255)),
                ('requestedQty', models.IntegerField()),
                ('receivedQty', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Complete', 'Complete')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BedHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=255)),
                ('patientId', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.bed')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('issuedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('receivingHospital', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('transportMode', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transferredBy', models.CharField(max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.patient'),
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qty', models.IntegerField()),
                ('type', models.CharField(choices=[('add', 'add'), ('dispense', 'dispense')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockHistory', to='api.medicineitem')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicineName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('timeGiven', models.TimeField()),
                ('nextDose', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='api.consultation')),
            ],
        ),
    ]
