# Generated by Django 6.0.7 on 2026-08-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_gradelevel_patient_guardianname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='assistingNurse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dismissalDestination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='fetcherIdImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='operationalNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='purposeOfVisit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
