# Generated by Django 6.0.7 on 2026-08-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consultation_assistingnurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='fetcherIdImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescriptionImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
