# Generated by Django 6.0.7 on 2026-08-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_consultation_fetcheridimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='timeOccupied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
