# Generated by Django 6.0.7 on 2026-08-03 10:43

from django.db import migrations


def seed_beds(apps, schema_editor):
    Bed = apps.get_model('api', 'Bed')
    if Bed.objects.count() == 0:
        beds_to_create = [
            Bed(bedNumber=i, status='Available')
            for i in range(1, 9)
        ]
        Bed.objects.bulk_create(beds_to_create)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bed_timeoccupied'),
    ]

    operations = [
        migrations.RunPython(seed_beds),
    ]
