# Generated by Django 6.0.7 on 2026-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20260803_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedhistory',
            name='patientId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bedhistory',
            name='patientName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
