# Generated by Django on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bedhistory_patientid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='unit',
            field=models.CharField(blank=True, default='Tablet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='prfNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='unitPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
