# Generated by Django 6.0.7 on 2026-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_purchaserequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='allottedTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bedhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
