# Generated by Django 6.0.7 on 2026-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bed_allottedtime_bed_reason_bedhistory_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineitem',
            name='batchNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='beginningQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='dispensed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='threshold',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='medicineitem',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock'), ('Healthy', 'Healthy')], default='Normal', max_length=50),
        ),
    ]
