# Generated by Django 6.0.7 on 2026-08-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seed_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineitem',
            name='category',
            field=models.CharField(default='Medicine', max_length=50),
        ),
    ]
