# Generated by Django 5.2.16 on 2026-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_appointmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='type',
            field=models.CharField(choices=[('medication', 'medication'), ('bed', 'bed'), ('general', 'general'), ('telemedicine_request', 'telemedicine_request'), ('appointment_request', 'appointment_request'), ('telemedicine_update', 'telemedicine_update'), ('appointment_update', 'appointment_update')], max_length=50),
        ),
    ]
