# Generated by Django 5.2.16 on 2026-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_appnotification_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemedicinerequest',
            name='secondary_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
