# Generated by Django 5.2.16 on 2026-09-18 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_telemedicinerequest_secondary_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_number', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('called', 'called'), ('done', 'done')], default='waiting', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.patient')),
            ],
        ),
    ]
