# Generated by Django 5.2.16 on 2026-09-20 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_patientqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAdvisory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Closed', max_length=50)),
                ('message', models.TextField(default='Welcome to the University Clinic! Standard operating hours are 8:00 AM to 5:00 PM.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
