# Generated by Django 5.2.16 on 2026-10-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicadvisory',
            name='auto_schedule',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinicadvisory',
            name='close_time',
            field=models.CharField(default='17:00', max_length=10),
        ),
        migrations.AddField(
            model_name='clinicadvisory',
            name='open_time',
            field=models.CharField(default='08:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
